### PR TITLE
Additions from Verovio testing

### PR DESCRIPTION
**Pull request by ahwitz**

### CODE REVIEW

**Comment by minamouse** [comment]
What does the "accidental coverage" file test? The way I did things was to make an html file to go with each group of mei files, so we can actually see them with verovio. If you don't want to add them though, I can just make an issue of it for now.

**Comment by ahwitz** [comment]
That file covers all possible values of the accid attribute (https://github.com/music-encoding/music-encoding/blob/develop/source/specs/mei-source.xml#L228) for testing https://github.com/rism-ch/verovio/issues/181. 

There's a lot of those that I don't know how to create in Sibelius. If @ahankinson is okay, doing that when you have time should be more than fine, as this is something I made and felt could be added to here, rather than something I made as part of this.

**Comment by ahwitz** [comment]
Don't merge this yet - gonna be finding more small oopsies all day.

**Comment by minamouse** [comment]
Ok sounds good! Let me know when you think it's ready :)

**Comment by ahwitz** [comment]
Should be ready with that last commit, but let @ahankinson sign off first.

**Comment by ahankinson** [comment]
Thanks!

**Comment by ahwitz** [comment]
My pleasure.

**Comment by ahankinson** [comment]
Where did you get the file from?

**Comment by ahwitz** [comment]
No way I'm remembering something four months after the fact, c'mon... This was done on my laptop at the MEC, I think. Might have been by hand?

**Comment by ahankinson** [comment]
ok, thanks!

**Pull request merged**
